package br.org.social;
import jakarta.persistence.*;import java.time.*;
@Entity class Student{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;@Column(nullable=false)String name;LocalDate birthDate;String responsibleName;boolean imageConsent;protected Student(){}Student(Org o,String n,LocalDate b,String r,boolean c){org=o;name=n;birthDate=b;responsibleName=r;imageConsent=c;}}
@Entity class ClassMeeting{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;@ManyToOne(optional=false)Workshop workshop;@Column(nullable=false)LocalDate meetingDate;String topic;protected ClassMeeting(){}ClassMeeting(Org o,Workshop w,LocalDate d,String t){org=o;workshop=w;meetingDate=d;topic=t;}}
@Entity class Enrollment{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;@ManyToOne(optional=false)Workshop workshop;@ManyToOne(optional=false)Student student;protected Enrollment(){}Enrollment(Org o,Workshop w,Student s){org=o;workshop=w;student=s;}}
@Entity class AttendanceRecord{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;@ManyToOne(optional=false)ClassMeeting meeting;@ManyToOne(optional=false)Student student;boolean present;protected AttendanceRecord(){}AttendanceRecord(Org o,ClassMeeting m,Student s,boolean p){org=o;meeting=m;student=s;present=p;}}
@Entity class PedagogicalNote{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;@ManyToOne(optional=false)ClassMeeting meeting;String author;@Column(length=5000)String text;protected PedagogicalNote(){}PedagogicalNote(Org o,ClassMeeting m,String a,String t){org=o;meeting=m;author=a;text=t;}}
interface Students extends org.springframework.data.jpa.repository.JpaRepository<Student,Long>{java.util.List<Student> findByOrgId(Long id);java.util.Optional<Student> findByIdAndOrgId(Long id,Long org);}
interface Meetings extends org.springframework.data.jpa.repository.JpaRepository<ClassMeeting,Long>{java.util.List<ClassMeeting> findByWorkshopIdAndOrgId(Long workshopId,Long org);java.util.Optional<ClassMeeting> findByIdAndOrgId(Long id,Long org);}
interface Enrollments extends org.springframework.data.jpa.repository.JpaRepository<Enrollment,Long>{java.util.List<Enrollment> findByWorkshopIdAndOrgId(Long workshopId,Long org);boolean existsByWorkshopIdAndStudentIdAndOrgId(Long w,Long s,Long org);}
interface Attendances extends org.springframework.data.jpa.repository.JpaRepository<AttendanceRecord,Long>{java.util.List<AttendanceRecord> findByMeetingIdAndOrgId(Long meetingId,Long org);java.util.Optional<AttendanceRecord> findByMeetingIdAndStudentIdAndOrgId(Long meetingId,Long studentId,Long org);}
interface Notes extends org.springframework.data.jpa.repository.JpaRepository<PedagogicalNote,Long>{java.util.List<PedagogicalNote> findByMeetingIdAndOrgId(Long meetingId,Long org);}
