package br.org.social;
import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
@io.swagger.v3.oas.annotations.tags.Tag(name="Acadêmico", description="Participantes, matrículas, encontros, frequência e registros pedagógicos") @RestController @RequestMapping("/api") class AcademicApi{
 final Members members;final Workshops workshops;final Students students;final Meetings meetings;final Enrollments enrollments;final Attendances attendances;final Notes notes;
 AcademicApi(Members m,Workshops w,Students s,Meetings mt,Enrollments en,Attendances at,Notes n){members=m;workshops=w;students=s;meetings=mt;enrollments=en;attendances=at;notes=n;}
 record StudentIn(String name,LocalDate birthDate,String responsibleName,boolean imageConsent){} record MeetingIn(LocalDate meetingDate,String topic){} record EnrollmentIn(Long studentId){} record Mark(Long studentId,boolean present){} record NoteIn(String text){}
 Org org(Authentication a){return members.findByEmailOrLogin(a.getName(),a.getName()).orElseThrow().org;}void manager(Authentication a){if(!List.of("ADMIN","COORDINATOR").contains(members.findByEmailOrLogin(a.getName(),a.getName()).orElseThrow().role))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Ação restrita à coordenação");}void educator(Authentication a){if(!List.of("ADMIN","COORDINATOR","INSTRUCTOR").contains(members.findByEmailOrLogin(a.getName(),a.getName()).orElseThrow().role))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Ação restrita à equipe pedagógica");}
 Workshop workshop(Long id,Long org){return workshops.findByIdAndOrgId(id,org).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 ClassMeeting meeting(Long id,Long org){return meetings.findByIdAndOrgId(id,org).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 @GetMapping("/students") List<Student> students(Authentication a){return students.findByOrgId(org(a).id);}
 @PostMapping("/students") Student addStudent(@RequestBody StudentIn i,Authentication a){manager(a);Org o=org(a);if(i.birthDate()!=null&&i.birthDate().isAfter(LocalDate.now()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Data de nascimento inválida");if(i.birthDate()!=null&&java.time.Period.between(i.birthDate(),LocalDate.now()).getYears()<18&&"ONG".equals(o.type))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"O cadastro de participante menor de idade não é permitido para organização do tipo ONG");if(i.birthDate()!=null&&java.time.Period.between(i.birthDate(),LocalDate.now()).getYears()<18&& (i.responsibleName()==null||i.responsibleName().isBlank()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Informe responsável para participante menor de idade");return students.save(new Student(o,i.name(),i.birthDate(),i.responsibleName(),i.imageConsent()));}
 @GetMapping("/workshops/{id}/meetings") List<ClassMeeting> meetings(@PathVariable Long id,Authentication a){return meetings.findByWorkshopIdAndOrgId(id,org(a).id);}
 @PostMapping("/workshops/{id}/meetings") ClassMeeting addMeeting(@PathVariable Long id,@RequestBody MeetingIn i,Authentication a){manager(a);Org o=org(a);return meetings.save(new ClassMeeting(o,workshop(id,o.id),i.meetingDate(),i.topic()));}
 @GetMapping("/workshops/{id}/enrollments") List<Enrollment> enrollments(@PathVariable Long id,Authentication a){Org o=org(a);workshop(id,o.id);return enrollments.findByWorkshopIdAndOrgId(id,o.id);}
 @PostMapping("/workshops/{id}/enrollments") Enrollment enroll(@PathVariable Long id,@RequestBody EnrollmentIn i,Authentication a){manager(a);Org o=org(a);Workshop w=workshop(id,o.id);Student s=students.findByIdAndOrgId(i.studentId(),o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(enrollments.existsByWorkshopIdAndStudentIdAndOrgId(id,s.id,o.id))throw new ResponseStatusException(HttpStatus.CONFLICT,"Participante já matriculado");return enrollments.save(new Enrollment(o,w,s));}
 @GetMapping("/meetings/{id}/attendance") List<AttendanceRecord> attendance(@PathVariable Long id,Authentication a){return attendances.findByMeetingIdAndOrgId(id,org(a).id);}
 @PutMapping("/meetings/{id}/attendance") List<AttendanceRecord> mark(@PathVariable Long id,@RequestBody List<Mark> marks,Authentication a){educator(a);Org o=org(a);ClassMeeting m=meeting(id,o.id);List<AttendanceRecord> out=new ArrayList<>();for(Mark mark:marks){Student s=students.findByIdAndOrgId(mark.studentId(),o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(!enrollments.existsByWorkshopIdAndStudentIdAndOrgId(m.workshop.id,s.id,o.id))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Participante não matriculado nesta oficina");AttendanceRecord r=attendances.findByMeetingIdAndStudentIdAndOrgId(id,s.id,o.id).orElse(new AttendanceRecord(o,m,s,mark.present()));r.present=mark.present();out.add(attendances.save(r));}return out;}
 @GetMapping("/meetings/{id}/notes") List<PedagogicalNote> notes(@PathVariable Long id,Authentication a){Org o=org(a);meeting(id,o.id);return notes.findByMeetingIdAndOrgId(id,o.id);}
 @PostMapping("/meetings/{id}/notes") PedagogicalNote addNote(@PathVariable Long id,@RequestBody NoteIn i,Authentication a){educator(a);Org o=org(a);return notes.save(new PedagogicalNote(o,meeting(id,o.id),a.getName(),i.text()));}
}

