package br.org.social;
import jakarta.persistence.*;import org.springframework.boot.*;import org.springframework.boot.autoconfigure.*;import org.springframework.context.annotation.*;import org.springframework.data.jpa.repository.*;import org.springframework.http.*;import org.springframework.security.config.annotation.web.builders.HttpSecurity;import org.springframework.security.core.Authentication;import org.springframework.security.core.userdetails.*;import org.springframework.security.crypto.bcrypt.*;import org.springframework.security.crypto.password.*;import org.springframework.security.web.SecurityFilterChain;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.math.*;import java.time.*;import java.util.*;
@SpringBootApplication public class App{public static void main(String[]a){SpringApplication.run(App.class,a);}}
@Entity class Org{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;String name,type;protected Org(){}Org(String n,String t){name=n;type=t;}}
@Entity class OrgPosition{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;String name,description;protected OrgPosition(){}OrgPosition(Org o,String n,String d){org=o;name=n;description=d;}}
@Entity class Member{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne Org org;@ManyToOne OrgPosition position;String name;@Column(unique=true)String email;@Column(unique=true)String login;String hash,role;boolean passwordSetupRequired;String setupTokenHash;Instant setupTokenExpiresAt;protected Member(){}Member(Org o,String e,String h){this(o,e,e,h,"ADMIN");}Member(Org o,String e,String h,String r){this(o,e,e,h,r);}Member(Org o,String l,String e,String h,String r){org=o;login=l;email=e;hash=h;role=r;}}
@Entity class Workshop{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne Org org;String name,description;boolean active=true;protected Workshop(){}Workshop(Org o,String n,String d){org=o;name=n;description=d;}}
@Entity class Project{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne Org org;String name,funder;BigDecimal budget;protected Project(){}Project(Org o,String n,String f,BigDecimal b){org=o;name=n;funder=f;budget=b;}}
@Entity class Expense{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne Org org;@ManyToOne Project project;@ManyToOne Workshop workshop;String description,category,documentName,documentKey,status="PENDING",approvedBy;BigDecimal amount;LocalDate expenseDate;protected Expense(){}Expense(Org o,Project p,Workshop w,String d,String c,BigDecimal a,LocalDate dt,String doc){org=o;project=p;workshop=w;description=d;category=c;amount=a;expenseDate=dt;documentName=doc;}}
interface Orgs extends JpaRepository<Org,Long>{} interface Members extends JpaRepository<Member,Long>{Optional<Member> findByEmail(String e);Optional<Member> findByLogin(String login);Optional<Member> findByEmailOrLogin(String email,String login);} interface Workshops extends JpaRepository<Workshop,Long>{List<Workshop> findByOrgId(Long id);Optional<Workshop> findByIdAndOrgId(Long id,Long org);} interface Projects extends JpaRepository<Project,Long>{List<Project> findByOrgId(Long id);Optional<Project> findByIdAndOrgId(Long id,Long org);} interface Expenses extends JpaRepository<Expense,Long>{List<Expense> findByOrgId(Long id);Optional<Expense> findByIdAndOrgId(Long id,Long org);}
@Configuration class Sec{
 private static final org.slf4j.Logger log=org.slf4j.LoggerFactory.getLogger(Sec.class);
 @Bean PasswordEncoder encoder(){return new BCryptPasswordEncoder();}
 @Bean org.springframework.security.config.annotation.web.configuration.WebSecurityCustomizer publicSetupWithoutSecurity(){return web->web.ignoring().requestMatchers("/api/setup");}
  @org.springframework.core.annotation.Order(2) @Bean SecurityFilterChain filter(HttpSecurity h,ApiTokens tokens)throws Exception{
  return h.csrf(c->c.disable())
   .cors(c->c.configurationSource(r->{var x=new org.springframework.web.cors.CorsConfiguration();x.setAllowedOrigins(List.of("http://localhost:5173"));x.setAllowedMethods(List.of("GET","POST","PUT","PATCH","OPTIONS"));x.setAllowedHeaders(List.of("*"));return x;}))
   .sessionManagement(s->s.sessionCreationPolicy(org.springframework.security.config.http.SessionCreationPolicy.STATELESS))
   .requestCache(c->c.disable())
   .authorizeHttpRequests(a->a.requestMatchers("/api/setup","/api/auth/login","/api/auth/password-setup/**","/api/health","/swagger-ui.html","/swagger-ui/**","/v3/api-docs/**").permitAll().anyRequest().authenticated())
   .httpBasic(b->b.disable()).formLogin(f->f.disable())
   .exceptionHandling(e->e.authenticationEntryPoint((request,response,exception)->{log.warn("auth_rejected method={} path={} bearerHeaderPresent={}",request.getMethod(),request.getRequestURI(),request.getHeader("Authorization")!=null);response.setStatus(401);response.setContentType("application/json");response.setCharacterEncoding("UTF-8");response.getWriter().write("{\"error\":\"Sessão inválida ou expirada. Faça login novamente.\"}");}))
   .addFilterBefore(new BearerTokenFilter(tokens),org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.class)
   .build();
 }
}
@io.swagger.v3.oas.annotations.tags.Tag(name="Organização e financeiro", description="Cadastro da organização, oficinas, projetos, despesas e decisões de prestação de contas") @RestController @RequestMapping("/api") class Api{private static final org.slf4j.Logger log=org.slf4j.LoggerFactory.getLogger(Api.class);final Orgs os;final Members ms;final Workshops ws;final Projects ps;final Expenses es;final PasswordEncoder enc;Api(Orgs o,Members m,Workshops w,Projects p,Expenses e,PasswordEncoder x){os=o;ms=m;ws=w;ps=p;es=e;enc=x;}record Setup(String organization,String organizationType,String login,String email,String password){}record WIn(String name,String description){}record PIn(String name,String funder,BigDecimal budget){}record EIn(Long projectId,Long workshopId,String description,String category,BigDecimal amount,LocalDate expenseDate,String documentName){}Member who(Authentication a){return ms.findByEmailOrLogin(a.getName(),a.getName()).orElseThrow();}Org tenant(Authentication a){return who(a).org;}void manager(Authentication a){if(!List.of("ADMIN","COORDINATOR").contains(who(a).role))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Ação restrita à coordenação");}
@io.swagger.v3.oas.annotations.security.SecurityRequirements @GetMapping("/health")Map health(){return Map.of("status","ok");}@io.swagger.v3.oas.annotations.security.SecurityRequirements @org.springframework.transaction.annotation.Transactional @PostMapping("/setup")ResponseEntity<?> setup(@RequestBody Setup s){log.info("signup_received type={} loginPresent={} emailPresent={}",s.organizationType(),s.login()!=null,s.email()!=null);if(s.password()==null||s.password().length()<10)return ResponseEntity.badRequest().body(Map.of("error","senha mínima: 10 caracteres"));if(s.login()==null||s.login().isBlank()||s.login().length()<3)return ResponseEntity.badRequest().body(Map.of("error","login deve ter pelo menos 3 caracteres"));if(!List.of("ONG","ESCOLA").contains(s.organizationType()))return ResponseEntity.badRequest().body(Map.of("error","Tipo deve ser ONG ou ESCOLA"));if(ms.findByEmailOrLogin(s.email(),s.login()).isPresent()){log.warn("signup_rejected reason=duplicate_email_or_login");return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("error","E-mail ou login já cadastrado"));}Org o=os.save(new Org(s.organization(),s.organizationType()));ms.save(new Member(o,s.login(),s.email(),enc.encode(s.password()),"ADMIN"));log.info("signup_created organizationId={}",o.id);return ResponseEntity.ok(Map.of("organizationId",o.id));}@GetMapping("/me")Map me(Authentication a){Member m=who(a);return Map.of("organization",m.org.name,"login",m.login==null?m.email:m.login,"email",m.email,"role",m.role);}
@GetMapping("/workshops")List<Workshop> workshops(Authentication a){return ws.findByOrgId(tenant(a).id);}@PostMapping("/workshops")Workshop addW(@RequestBody WIn i,Authentication a){manager(a);return ws.save(new Workshop(tenant(a),i.name(),i.description()));}@PatchMapping("/workshops/{id}/close")Workshop close(@PathVariable Long id,Authentication a){manager(a);Workshop w=ws.findByIdAndOrgId(id,tenant(a).id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));w.active=false;return ws.save(w);}
@GetMapping("/projects")List<Project> projects(Authentication a){return ps.findByOrgId(tenant(a).id);}@PostMapping("/projects")Project addP(@RequestBody PIn i,Authentication a){manager(a);return ps.save(new Project(tenant(a),i.name(),i.funder(),i.budget()));}@GetMapping("/expenses")List<Expense> expenses(Authentication a){return es.findByOrgId(tenant(a).id);}@PostMapping("/expenses")Expense addE(@RequestBody EIn i,Authentication a){manager(a);Org o=tenant(a);Project p=ps.findByIdAndOrgId(i.projectId(),o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));Workshop w=i.workshopId()==null?null:ws.findByIdAndOrgId(i.workshopId(),o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));return es.save(new Expense(o,p,w,i.description(),i.category(),i.amount(),i.expenseDate(),i.documentName()));}@PostMapping("/expenses/{id}/{decision}")Expense decide(@PathVariable Long id,@PathVariable String decision,Authentication a){manager(a);if(!List.of("approve","reject").contains(decision))throw new ResponseStatusException(HttpStatus.BAD_REQUEST);Expense e=es.findByIdAndOrgId(id,tenant(a).id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));e.status=decision.equals("approve")?"APPROVED":"REJECTED";e.approvedBy=a.getName();return es.save(e);}}
