package br.org.social;
import jakarta.persistence.*;import org.springframework.data.jpa.repository.JpaRepository;import org.springframework.security.core.Authentication;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import org.springframework.http.HttpStatus;import java.util.*;import java.math.BigDecimal;
@Entity class Instructor{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;String name,area,contact;protected Instructor(){}Instructor(Org o,String n,String a,String c){org=o;name=n;area=a;contact=c;}}
@Entity class WorkshopInstructor{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@ManyToOne(optional=false)Org org;@ManyToOne(optional=false)Workshop workshop;@ManyToOne(optional=false)Instructor instructor;protected WorkshopInstructor(){}WorkshopInstructor(Org o,Workshop w,Instructor i){org=o;workshop=w;instructor=i;}}
interface MemberDirectory extends JpaRepository<Member,Long>{List<Member> findByOrgId(Long org);Optional<Member> findByIdAndOrgId(Long id,Long org);}
interface OrgPositions extends JpaRepository<OrgPosition,Long>{List<OrgPosition> findByOrgId(Long org);Optional<OrgPosition> findByIdAndOrgId(Long id,Long org);Optional<OrgPosition> findByOrgIdAndNameIgnoreCase(Long org,String name);}
interface Instructors extends JpaRepository<Instructor,Long>{List<Instructor> findByOrgId(Long org);Optional<Instructor> findByIdAndOrgId(Long id,Long org);}
interface WorkshopInstructors extends JpaRepository<WorkshopInstructor,Long>{List<WorkshopInstructor> findByWorkshopIdAndOrgId(Long workshop,Long org);boolean existsByWorkshopIdAndInstructorIdAndOrgId(Long workshop,Long instructor,Long org);}
@io.swagger.v3.oas.annotations.tags.Tag(name="Equipe e relatórios", description="Usuários, instrutores, vínculos com oficinas e relatórios") @RestController @RequestMapping("/api") class ExtensionsApi{
 final Members members;final MemberDirectory directory;final OrgPositions positions;final PasswordEncoder encoder;final Instructors instructors;final Workshops workshops;final WorkshopInstructors assignments;final Projects projects;final Expenses expenses;final Students students;
 ExtensionsApi(Members m,MemberDirectory d,OrgPositions op,PasswordEncoder e,Instructors i,Workshops w,WorkshopInstructors a,Projects p,Expenses x,Students s){members=m;directory=d;positions=op;encoder=e;instructors=i;workshops=w;assignments=a;projects=p;expenses=x;students=s;}
 record UserIn(String name,String login,String email){}record PositionIn(String name,String description){}record PositionAssign(Long positionId){}record InstructorIn(String name,String area,String contact){}record Assign(Long instructorId){}
 Member actor(Authentication a){return members.findByEmailOrLogin(a.getName(),a.getName()).orElseThrow();}Org org(Authentication a){return actor(a).org;}void admin(Authentication a){if(!"ADMIN".equals(actor(a).role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);}
 @GetMapping("/users")List<Map<String,Object>> users(Authentication a){admin(a);return directory.findByOrgId(org(a).id).stream().map(this::userView).toList();}
 Map<String,Object> userView(Member u){Map<String,Object> view=new LinkedHashMap<>();view.put("id",u.id);view.put("name",u.name==null?"":u.name);view.put("login",u.login);view.put("email",u.email);view.put("permissionRole",u.role);view.put("positionId",u.position==null?null:u.position.id);view.put("positionName",u.position==null?null:u.position.name);return view;}
 @PostMapping("/users")Map<String,Object> addUser(@RequestBody UserIn i,Authentication a){admin(a);if(i.name()==null||i.name().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Informe o nome do membro");if(i.login()==null||i.login().isBlank()||i.login().trim().length()<3)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Login deve ter pelo menos 3 caracteres");if(i.email()==null||!i.email().matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"E-mail inválido");String login=i.login().trim();String email=i.email().trim().toLowerCase(Locale.ROOT);if(members.findByEmailOrLogin(email,login).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"E-mail ou login já cadastrado");byte[] bytes=new byte[32];new java.security.SecureRandom().nextBytes(bytes);String setupToken=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);Member u=new Member(org(a),login,email,null,"INSTRUCTOR");u.name=i.name().trim();u.passwordSetupRequired=true;u.setupTokenHash=TokenSecurity.hash(setupToken);u.setupTokenExpiresAt=java.time.Instant.now().plus(java.time.Duration.ofDays(7));u=directory.save(u);Map<String,Object> result=userView(u);result.put("setupToken",setupToken);result.put("setupTokenExpiresAt",u.setupTokenExpiresAt.toString());return result;}
 @GetMapping("/positions")List<Map<String,Object>> positions(Authentication a){admin(a);return this.positions.findByOrgId(org(a).id).stream().map(p->Map.<String,Object>of("id",p.id,"name",p.name,"description",p.description==null?"":p.description)).toList();}
 @PostMapping("/positions")Map<String,Object> addPosition(@RequestBody PositionIn input,Authentication a){admin(a);if(input.name()==null||input.name().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Informe o nome do cargo");Org o=org(a);String name=input.name().trim();if(positions.findByOrgIdAndNameIgnoreCase(o.id,name).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Esse cargo já existe");OrgPosition p=positions.save(new OrgPosition(o,name,input.description()==null?"":input.description().trim()));return Map.of("id",p.id,"name",p.name,"description",p.description);}
 @PutMapping("/users/{id}/position")Map<String,Object> assignPosition(@PathVariable Long id,@RequestBody PositionAssign input,Authentication a){admin(a);Org o=org(a);Member user=directory.findByIdAndOrgId(id,o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Membro não encontrado nesta organização"));if(input.positionId()==null)user.position=null;else user.position=positions.findByIdAndOrgId(input.positionId(),o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Cargo não encontrado nesta organização"));return userView(directory.save(user));}
 @org.springframework.transaction.annotation.Transactional
 @PostMapping("/users/{id}/password-reset")Map<String,Object> resetPassword(@PathVariable Long id,Authentication a){admin(a);Org o=org(a);Member user=directory.findByIdAndOrgId(id,o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Membro não encontrado nesta organização"));byte[] bytes=new byte[32];new java.security.SecureRandom().nextBytes(bytes);String setupToken=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);user.hash=null;user.passwordSetupRequired=true;user.setupTokenHash=TokenSecurity.hash(setupToken);user.setupTokenExpiresAt=java.time.Instant.now().plus(java.time.Duration.ofDays(7));directory.save(user);return Map.of("setupToken",setupToken,"setupTokenExpiresAt",user.setupTokenExpiresAt.toString());}
 @GetMapping("/instructors")List<Instructor> instructors(Authentication a){return instructors.findByOrgId(org(a).id);}
 @PostMapping("/instructors")Instructor addInstructor(@RequestBody InstructorIn i,Authentication a){if(!List.of("ADMIN","COORDINATOR").contains(actor(a).role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);if(i.name()==null||i.name().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Informe o nome do instrutor");if(i.contact()==null||!i.contact().matches("^\\(\\d{2}\\) (?:\\d{4}|\\d{5})-\\d{4}$"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Informe um telefone válido com DDD, por exemplo (11) 91234-5678");return instructors.save(new Instructor(org(a),i.name().trim(),i.area(),i.contact()));}
 @GetMapping("/workshops/{id}/instructors")List<WorkshopInstructor> workshopInstructors(@PathVariable Long id,Authentication a){Org o=org(a);workshops.findByIdAndOrgId(id,o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));return assignments.findByWorkshopIdAndOrgId(id,o.id);}
 @PostMapping("/workshops/{id}/instructors")WorkshopInstructor assign(@PathVariable Long id,@RequestBody Assign input,Authentication a){if(!List.of("ADMIN","COORDINATOR").contains(actor(a).role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);Org o=org(a);Workshop w=workshops.findByIdAndOrgId(id,o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));Instructor i=instructors.findByIdAndOrgId(input.instructorId(),o.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(assignments.existsByWorkshopIdAndInstructorIdAndOrgId(id,i.id,o.id))throw new ResponseStatusException(HttpStatus.CONFLICT,"Instrutor já designado");return assignments.save(new WorkshopInstructor(o,w,i));}
 @GetMapping("/reports/summary")Map<String,Object> summary(Authentication a){Org o=org(a);List<Expense> rows=expenses.findByOrgId(o.id);BigDecimal spent=rows.stream().filter(e->"APPROVED".equals(e.status)).map(e->e.amount).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add);return Map.of("workshops",workshops.findByOrgId(o.id).size(),"participants",students.findByOrgId(o.id).size(),"projects",projects.findByOrgId(o.id).size(),"expenses",rows.size(),"approvedExpenses",spent,"pendingExpenses",rows.stream().filter(e->"PENDING".equals(e.status)).count());}

 @GetMapping(value="/reports/expenses.csv",produces="text/csv;charset=UTF-8") org.springframework.http.ResponseEntity<String> expenseCsv(Authentication a){StringBuilder csv=new StringBuilder("﻿data,projeto,fonte,categoria,descricao,valor,status,comprovante\n");for(Expense e:expenses.findByOrgId(org(a).id)){csv.append(csv(e.expenseDate==null?"":e.expenseDate.toString())).append(',').append(csv(e.project.name)).append(',').append(csv(e.project.funder)).append(',').append(csv(e.category)).append(',').append(csv(e.description)).append(',').append(e.amount).append(',').append(csv(e.status)).append(',').append(csv(e.documentName)).append('\n');}return org.springframework.http.ResponseEntity.ok().header("Content-Disposition","attachment; filename=despesas.csv").body(csv.toString());}
 String csv(String value){return "\""+(value==null?"":value.replace("\"","\"\""))+"\"";}
}
